apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  template:
    spec:
      initContainers:
        - name: transfer-file-ownership
          image: sourcegraph/alpine:3.12@sha256:133a0a767b836cf86a011101995641cf1b5cbefb3dd212d78d7be145adde636d
          command: ["sh", "-c", "chown -R 100:101 /data"]
          volumeMounts:
          - mountPath: /data
            name: minio-data
          securityContext:
            runAsUser: 0
